(define (problem blocks-3)
    (:domain gripper)
    (:requirements :strips)
  	(:objects red green blue)
    (:init
        (on-ground green)
        (on green red)
        (on red blue)
        (on-top blue)
        (distinct red green)
        (distinct green red)
        (distinct red blue)
        (distinct blue red)
        (distinct green blue)
        (distinct blue green)
    )
    (:goal (and
        (on-ground red)
        (on red green)
        (on green blue)
        (on-top blue)
      )
    )
)