function Lh = compute_Lh(itrn, itst, x, h)
% Lh = compute_Lh(itrn, itst, x, h)
%
%   Computes the average log-likelihood over training/test splits generated
%   by crossval for a fixed kernel bandwidth h.
%
%   Parameters:
%       itrn, itst - data splits (indices) generated by crossval()
%       x - the data itself
%       h - kernel bandwidth
%
%   Returns:
%       Lh - average log-likelihood over training/test splits

result = zeros(size(itrn));
for i = 1:length(itrn)
    result(i) = sum(log(my_parzen(x(itst{i}), x(itrn{i}), h)));
end
Lh = sum(result) / length(itrn);
