source 'https://rubygems.org'

gem 'rspec', '< 4.0'
gem 'spork'
gem 'guard-spork'
gem 'guard-rspec'
gem 'guard'
gem 'listen', '~> 2.7'
gem 'formatador', '>= 0.2.4'
gem 'gserver' # GServer was extracted from stdlib in Ruby 2.2.0
