(define (problem logistics-3)
    (:domain gripper)
    (:requirements :strips)
  	(:objects car c1 c2 c3 c4 c5 c6 A B C D E)
    (:init
        (has c1 A)
        (has c2 B)
        (has c3 C)
        (has c4 D)
        (has c5 E)
        (has c1 car)
        (free car)
        (sibling c1 c2)
        (sibling c1 c3)
        (sibling c1 c4)
        (sibling c2 c1)
        (sibling c2 c3)
        (sibling c3 c1)
        (sibling c3 c2)
        (sibling c3 c4)
        (sibling c3 c5)
        (sibling c3 c6)
        (sibling c4 c1)
        (sibling c4 c3)
        (sibling c5 c3)
        (sibling c5 c6)
        (sibling c6 c3)
        (sibling c6 c5)
        (is-car car)
    )
    (:goal
        (and
            (has c1 D)
            (has c2 C)
            (has c2 E)
            (has c5 A)
            (has c6 B)
            (has c1 car)
            (free car)
        )
    )
)