(define (problem logistics-3)
    (:domain gripper)
    (:requirements :strips)
  	(:objects p1 p2 p3 p4 o1 o2 o3)
    (:init
        (is_tile o1)
        (is_tile o2)
        (is_tile o3)
        (is_pos p1)
        (is_pos p2)
        (is_pos p3)
        (is_pos p4)
        (free p2)
        (next p1 p2)
        (next p1 p3)
        (next p2 p1)
        (next p2 p4)
        (next p3 p1)
        (next p3 p4)
        (next p4 p2)
        (next p4 p3)
        (on p1 o3)
        (on p3 o2)
        (on p4 o1)
    )
    (:goal
        (and
            (on p1 o1)
            (on p2 o2)
            (on p3 o3)
            (free p4)
        )
    )
)